usr/share/man/man3/Zonemaster::CLI.3pm
usr/share/perl5/Zonemaster/CLI.pm
usr/share/perl5/auto/share/dist/Zonemaster-CLI/fr.po
usr/share/perl5/auto/share/dist/Zonemaster-CLI/en.po
usr/share/perl5/auto/share/dist/Zonemaster-CLI/sv.po
usr/share/perl5/auto/share/dist/Zonemaster-CLI/locale/fr/LC_MESSAGES/Zonemaster-CLI.mo
usr/share/perl5/auto/share/dist/Zonemaster-CLI/locale/en/LC_MESSAGES/Zonemaster-CLI.mo
usr/share/perl5/auto/share/dist/Zonemaster-CLI/locale/sv/LC_MESSAGES/Zonemaster-CLI.mo
